# Generated by Django 4.2.20 on 2025-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_footballfield_image_booking'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='stadium_boo_booking_4eb40b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time'], name='stadium_boo_start_t_aa29fd_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['end_time'], name='stadium_boo_end_tim_e0f7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['field'], name='stadium_boo_field_i_8425fa_idx'),
        ),
    ]
